### ISSUE TITLE
卷积自编码器

### ISSUE THREAD

**Issue by fangxin-debug** [Nana0606/Autoencoder#1]
您好，关于卷积自编码器我有一个疑问 关于损失函数，为什么使用的不是 mse 而是 binary_crossentropy？

**Comment by XingdaChen1996** [comment]
求的就是mse吧，回归问题，不是分类问题

**Comment by Trouverecc** [comment]
您好，请问卷积自编码器程序可以跑，但是绘图部分报错如下该如何处理啊，谢谢！
Traceback (most recent call last):
  File "D:\...\conv_autoencoder.py", line 122, in <module>
    plot_accuray(history_record)
  File "D:\...\conv_autoencoder.py", line 66, in plot_accuray
    accuracy = history_record.history["acc"]
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'acc'
